# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network requests synchronously during user interaction.
inhibit_all_warnings!

target 'Runner' do
  use_frameworks!
  
  # Firebase pods for push notifications
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
